language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3
install:
  - pip install -r requirements/development.txt -r requirements/production.txt
  - python setup.py install
script:
  - coverage run setup.py test
  - coverage report --show-missing
after_success:
  - coveralls
notifications:
    email: aaron.iles+travis-ci@gmail.com
